# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 335a5b0e9c2cef8abad240aa975e3bdae7b8b8eb696a11821eb93ceed73174301f1ee965e167c5d0d80d00cfb156120ed8b30566567671055b97468560bb021f

test:
  secret_key_base: e701f450390561d91b3408f25c70b0362d1e6726939d081dd637d1ee727c413a53b0e54139f03a8ee066ad66adb79661c181b1cf2f2884bac7040c217c7347b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
